# -*- coding: utf-8 -*-
"""vinculo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPIQI155OpTUZ4mPz61uxNfgp4pzGf8F
"""

import tkinter as tk
import random

def crear_ventana_con_destellos():
    # Configuración de la ventana principal
    root = tk.Tk()
    root.title("El Santuario Solar")
    root.geometry("800x600")
    root.configure(bg='#050d18')  # Fondo azul oscuro noche

    # Canvas es el área donde se dibujarán los destellos
    canvas = tk.Canvas(root, width=800, height=600, bg='#050d18', highlightthickness=0)
    canvas.pack()

    def generar_destello():
        # 1. Coordenadas aleatorias dentro de la ventana
        x = random.randint(0, 800)
        y = random.randint(0, 600)

        # 2. Tamaño aleatorio del destello
        size = random.randint(2, 6)

        # 3. Dibujar el óvalo (círculo) color dorado
        # El ID nos permite identificar este objeto específico
        destello_id = canvas.create_oval(
            x, y, x + size, y + size,
            fill='#FFD700',
            outline='#FFF8DC'
        )

        # 4. Programar la eliminación del destello (parpadeo)
        # El destello desaparecerá después de 1000ms (1 segundo)
        root.after(1000, lambda: canvas.delete(destello_id))

        # 5. Programar el siguiente destello
        # 150ms de espera entre destellos (puedes cambiar este valor)
        root.after(150, generar_destello)

    # Iniciar el bucle de destellos
    generar_destello()

    # Iniciar el bucle principal de la ventana
    root.mainloop()

if __name__ == "__main__":
    crear_ventana_con_destellos()